[database]
server = "127.0.0.1"
port = 3306
db_name = "querty"
user = "asdf"
pass = "asdf"

[solr]
server = "localhost"
port = 8983
collection = "querty"
path_to_solr = "~/solr-8.11.1/bin/solr"             # $SOLR_PATH will overwrite it if it is defined
path_to_solr_config = "~/querty/config/solr"        # $SOLR_CONFIG_PATH will overwrite it if it is defined
